import img_1_1 from "./img-card/card-1/card-img-5-1-1.jpeg";
import img_2_1 from "./img-card/card-2/card-img-5-2-1.jpeg";
import img_3_1 from "./img-card/card-3/card-img-5-3-1.jpeg";
import img_4_1 from "./img-card/card-4/card-img-5-4-1.jpeg";
import img_5_1 from "./img-card/card-5/card-img-5-5-1.jpeg";
import img_6_1 from "./img-card/card-6/card-img-5-6-1.jpeg";
import img_7_1 from "./img-card/card-7/card-img-5-7-1.jpeg";
import img_8_1 from "./img-card/card-8/card-img-5-8-1.jpeg";

export const card_details = [
  {
    _id: "1",
    image1: img_1_1,
    name: "Best Western Cedars Hotel",
    discount: "20",
    beds: "6",
    bath: "3",
    area: "1200",
    rating: "4.8",
    review: "28",
    price: "26,000",
  },
  {
    _id: "2",
    image1: img_2_1,
    name: "Bell By Greene King Inns",
    discount: "10",
    beds: "6",
    bath: "3",
    area: "1100",
    rating: "4.4",
    review: "198",
    price: "250,000",
  },
  {
    _id: "3",
    image1: img_3_1,
    name: "Half Moon, Sherborne By Marston's Inns",
    discount: "10",
    beds: "4",
    bath: "2",
    area: "800",
    rating: "3.6",
    review: "16",
    price: "278,00",
  },
  {
    _id: "4",
    image1: img_4_1,
    name: "White Horse Hotel By Greene King Inns",
    discount: "10",
    beds: "6",
    bath: "3",
    area: "1200",
    rating: "4.8",
    review: "34",
    price: "40,000",
  },
  {
    _id: "5",
    image1: img_5_1,
    name: "Ship And Castle Hotel",
    discount: "10",
    beds: "5",
    bath: "3",
    area: "1200",
    rating: "3.4",
    review: "340",
    price: "147,000",
  },
  {
    _id: "6",
    image1: img_6_1,
    name: "Unicorn, Gunthorpe By Marston's Inns",
    discount: "10",
    beds: "6",
    bath: "3",
    area: "1200",
    rating: "3",
    review: "481",
    price: "282,000",
  },
  {
    _id: "7",
    image1: img_7_1,
    name: "The Windmill Family & Commercial Hotel",
    discount: "10",
    beds: "2",
    bath: "1",
    area: "400",
    rating: "3.8",
    review: "508",
    price: "90,000",
  },
  {
    _id: "8",
    image1: img_8_1,
    name: "Holiday Inn Express Ramsgate Minster, An IHG Hotel",
    discount: "10",
    beds: "10",
    bath: "5",
    area: "2400",
    rating: "4.9",
    review: "300",
    price: "300,000",
  },
];
