const mongoose = require("mongoose");

const propertyDetailsSchema = new mongoose.Schema({
  id: Number,
  email: String,
  propertyName: String,
  propertyType: String,
  rentalForm: String,
  country: String,
  city: String,
  state: String,
  street: String,
  roomNumber: String,
  postalCode: Number,
  propertyInformation: String,
  bedroom: Number,
  baths: Number,
  beds: Number,
  parking: Boolean,
  area: Number,
  hostImage: String,
  hostName: String,
  hostInformation: String,
  hostJoinDate: String,
  hostFastResponse: { type: String, default: "within few hours" },
  hostResponseRate: { type: Number, default: 100 },
  amenities: {
    key: Boolean,
    luggage: Boolean,
    shower: Boolean,
    spa: Boolean,
    swimmingPool: Boolean,
    tv: Boolean,
    utensils: Boolean,
    wifi: Boolean,
    bath_a: Boolean,
    bed_a: Boolean,
    parking_a: Boolean,
    kitchen: Boolean,
    hotTube: Boolean,
    jacuzzi: Boolean,
    security: Boolean,
    playArea: Boolean,
    cinemaHall: Boolean,
    frontPorch: Boolean,
    gym: Boolean,
    airConditioning: Boolean,
    balcony: Boolean,
  },
  mainImage: String,
  image1: String,
  image2: String,
  image3: String,
  image4: String,
  price: Number,
  rent: Number,
  delarChargeForBuy: Number,
  delarChargeForRent: Number,
  discount: Number,
  rating: { type: Number, default: 5 },
});

const Property = mongoose.model(
  "propertyDetails",
  propertyDetailsSchema,
  "propertyDetails"
);

module.exports = Property;
