import house_1 from "../images/house-1.jpg";
import hall_1 from "../images/hall-1.jpg";
import bed_1 from "../images/bedroom-1.jpg";
import kitchen_1 from "../images/kitchen-1.jpg";
import swimming_1 from "../images/swimming-1.jpg";
import host_1 from "../images/host-1.jpg";

import house_2 from "../images/house-2.jpg";
import hall_2 from "../images/hall-2.jpg";
import bed_2 from "../images/bedroom-2.jpg";
import kitchen_2 from "../images/kitchen-2.jpg";
import swimming_2 from "../images/swimming-2.jpg";
import host_2 from "../images/host-2.jpg";

import house_3 from "../images/house-3.jpg";
import hall_3 from "../images/hall-3.jpg";
import bed_3 from "../images/bedroom-3.jpg";
import kitchen_3 from "../images/kitchen-3.jpg";
import swimming_3 from "../images/swimming-3.jpg";
import host_3 from "../images/host-3.jpg";

import house_4 from "../images/house-4.jpg";
import hall_4 from "../images/hall-4.jpg";
import bed_4 from "../images/bedroom-4.jpg";
import kitchen_4 from "../images/kitchen-4.jpg";
import swimming_4 from "../images/swimming-4.jpg";
import host_4 from "../images/host-4.jpg";

import house_5 from "../images/house-5.jpg";
import hall_5 from "../images/hall-5.jpg";
import bed_5 from "../images/bedroom-5.jpg";
import kitchen_5 from "../images/kitchen-5.jpg";
import swimming_5 from "../images/swimming-5.jpg";
import host_5 from "../images/host-5.jpg";

import house_6 from "../images/house-6.jpg";
import hall_6 from "../images/hall-6.jpg";
import bed_6 from "../images/bedroom-6.jpg";
import kitchen_6 from "../images/kitchen-6.jpg";
import swimming_6 from "../images/swimming-6.jpg";
import host_6 from "../images/host-6.jpg";

import house_7 from "../images/house-7.jpg";
import hall_7 from "../images/hall-7.jpg";
import bed_7 from "../images/bedroom-7.jpg";
import kitchen_7 from "../images/kitchen-7.jpg";
import swimming_7 from "../images/swimming-7.jpg";
import host_7 from "../images/host-7.jpg";

import house_8 from "../images/house-8.jpg";
import hall_8 from "../images/hall-8.jpg";
import bed_8 from "../images/bedroom-8.jpg";
import kitchen_8 from "../images/kitchen-8.jpg";
import swimming_8 from "../images/swimming-8.jpg";
import host_8 from "../images/host-8.jpg";

const rating = 5;

const Property_Details = [
  {
    id: 1,
    discount: 20,
    house_image: house_8,
    hall_image: hall_8,
    bed_image: bed_8,
    kitchen_image: kitchen_8,
    swimming_image: swimming_8,
    name: "Holiday Inns Express Ramsgate Minster, An IHG Hotel",
    price: 3750000,
    rent: 37500,
    DelarChargeForRent: 2000,
    DelarChargeForBuy: 20000,
    rating: rating,
    review: 5,
    city: "Rajkot, Gujarat",
    beds: 10,
    baths: 5,
    area: 2400,
    parking: true,
    host_img: host_8,
    host_name: "Ms. Olivia Holiday",
    property_information:
      "At Holiday Inn Express Ramsgate Minster, An IHG Hotel, guests can enjoy accommodation with amenities including a terrace and complimentary WiFi. Private bathrooms with bidet, hairdryer, and free toiletries are available, along with bicycle and car rental services. Guests can also enjoy cycling nearby, although outdoor swimming pool, bar, shared lounge, garden, and barbecue facilities are not provided.",
    host_information:
      "Ms. Olivia Holiday is a rising star in the hospitality industry, known for her innovative approach to hotel management. With a background in digital marketing and guest relations, she has leveraged technology to enhance the guest experience and drive revenue growth. Ms. Holiday's passion for hospitality and commitment to excellence make her a valuable asset to any hotel team.",
    host_join_date: "Nov 2023",
    host_response_rate: 100,
    host_fast_response: "within few hours",
    key: true,
    luggage: true,
    shower: true,
    spa: true,
    swimmingPool: true,
    tv: true,
    utensils: true,
    wifi: true,
    bath_a: true,
    bed_a: true,
    parking_a: true,
    kitchen: true,
    hotTube: true,
    jacuzzi: true,
    security: true,
    playArea: true,
    cinemaHall: true,
    frontPorch: true,
    gym: true,
    airConditioning: true,
    balcony: true,
  },
  {
    id: 2,
    username: "user2",
    discount: 20,
    house_image: house_7,
    hall_image: hall_7,
    bed_image: bed_7,
    kitchen_image: kitchen_7,
    swimming_image: swimming_7,
    name: "The Windmill Family & Commercial Hotel",
    price: 90000,
    rent: 9000,
    DelarChargeForRent: 2000,
    DelarChargeForBuy: 20000,
    rating: rating,
    review: 5,
    city: "Rajkot, Gujarat",
    beds: 2,
    baths: 1,
    area: 400,
    parking: true,
    property_information:
      "The Windmill Family & Commercial Hotel provides accommodation with a bar, shared lounge, garden, barbecue facilities, and complimentary WiFi. Private bathrooms with bidet, hairdryer, and free toiletries are also available. Unfortunately, outdoor swimming pool, terrace, bicycle rental service, car rental service, and cycling nearby are not provided.",
    host_img: host_7,
    host_name: "Mr. Michael Windmill",
    host_information:
      "Mr. Michael Windmill is a seasoned hotel executive with a track record of success in the industry. With a career spanning several decades, he has held leadership roles in various hotel chains, overseeing operations and driving business growth. Mr. Windmill's strategic vision and hands-on approach have helped him navigate the challenges of the ever-evolving hospitality landscape.",
    host_join_date: "Jun 2023",
    host_response_rate: 100,
    host_fast_response: "within few hours",
    key: true,
    luggage: true,
    shower: true,
    spa: true,
    swimmingPool: true,
    tv: true,
    utensils: true,
    wifi: true,
    bath_a: true,
    bed_a: true,
    parking_a: true,
    kitchen: true,
    hotTube: true,
    jacuzzi: true,
    security: true,
    playArea: true,
    cinemaHall: true,
    frontPorch: true,
    gym: true,
    airConditioning: true,
    balcony: true,
  },

  {
    id: 3,
    username: "user3",
    discount: 10,
    house_image: house_3,
    hall_image: hall_3,
    bed_image: bed_3,
    kitchen_image: kitchen_3,
    swimming_image: swimming_3,
    name: "Half Moon, Sherborne By Marston's Inns",
    price: 278000,
    rent: 2780,
    DelarChargeForRent: 2000,
    DelarChargeForBuy: 20000,
    rating: rating,
    review: 5,
    city: "Rajkot, Gujarat",
    beds: 4,
    baths: 2,
    area: 800,
    parking: false,
    host_img: host_3,
    host_name: "Mr. David Marston",
    property_information:
      "At Half Moon, Sherborne By Marston's Inns, guests can expect accommodation with complimentary WiFi, private bathrooms with bidet, hairdryer, and free toiletries. However, amenities like outdoor swimming pool, bar, shared lounge, garden, barbecue facilities, terrace, bicycle rental service, car rental service, and cycling nearby are not provided.",
    host_information:
      "Mr. David Marston is a prominent figure in the hospitality sector, known for his strategic leadership and vision. As the CEO of a renowned hotel chain, he has spearheaded initiatives to enhance guest satisfaction and drive business growth. With a background in hotel management and marketing, Mr. Marston brings a wealth of knowledge and expertise to the industry.",
    host_join_date: "May 2023",
    host_response_rate: 100,
    host_fast_response: "within few hours",
    key: true,
    luggage: true,
    shower: true,
    spa: true,
    swimmingPool: true,
    tv: true,
    utensils: true,
    wifi: true,
    bath_a: true,
    bed_a: true,
    parking_a: true,
    kitchen: true,
    hotTube: true,
    jacuzzi: true,
    security: true,
    playArea: true,
    cinemaHall: true,
    frontPorch: true,
    gym: true,
    airConditioning: true,
    balcony: true,
  },
  {
    id: 4,
    username: "user4",
    discount: 10,
    house_image: house_4,
    hall_image: hall_4,
    bed_image: bed_4,
    kitchen_image: kitchen_4,
    swimming_image: swimming_4,
    name: "White Horse Hotel By Greene King Inns",
    price: 40000,
    rent: 400,
    DelarChargeForRent: 2000,
    DelarChargeForBuy: 20000,
    rating: rating,
    review: 5,
    city: "Rajkot, Gujarat",
    beds: 6,
    baths: 3,
    area: 1200,
    parking: true,
    host_img: host_4,
    host_name: "Mrs. Samantha White",
    property_information:
      "The White Horse Hotel By Greene King Inns offers accommodation with amenities including an outdoor swimming pool, bar, complimentary WiFi, private bathrooms with bidet, hairdryer, and free toiletries. Unfortunately, shared lounge, garden, barbecue facilities, terrace, bicycle rental service, car rental service, and cycling nearby are not available.",
    host_information:
      "Mrs. Samantha White is a respected hotel owner and operator with a passion for delivering exceptional service. With a background in luxury hospitality, she has cultivated a reputation for elegance and sophistication in her establishments. Mrs. White's attention to detail and commitment to excellence have earned her properties acclaim from discerning travelers around the world.",
    host_join_date: "Jan 2024",
    host_response_rate: 100,
    host_fast_response: "within few hours",
    key: true,
    luggage: true,
    shower: true,
    spa: true,
    swimmingPool: true,
    tv: true,
    utensils: true,
    wifi: true,
    bath_a: true,
    bed_a: true,
    parking_a: true,
    kitchen: true,
    hotTube: true,
    jacuzzi: true,
    security: true,
    playArea: true,
    cinemaHall: true,
    frontPorch: true,
    gym: true,
    airConditioning: true,
    balcony: true,
  },
  {
    id: 5,
    username: "user5",
    discount: 10,
    house_image: house_5,
    hall_image: hall_5,
    bed_image: bed_5,
    kitchen_image: kitchen_5,
    swimming_image: swimming_5,
    name: "Ship And Castle Hotel",
    price: 147000,
    rent: 1470,
    DelarChargeForRent: 2000,
    DelarChargeForBuy: 20000,
    rating: rating,
    review: 5,
    city: "Rajkot, Gujarat",
    beds: 5,
    baths: 3,
    area: 1200,
    parking: true,
    host_img: host_5,
    host_name: "Mr. William Ship",
    property_information:
      "Ship And Castle Hotel provides accommodation with a bar and complimentary WiFi, as well as private bathrooms with bidet, hairdryer, and free toiletries. However, amenities such as outdoor swimming pool, shared lounge, garden, barbecue facilities, terrace, bicycle rental service, car rental service, and cycling nearby are not provided.",
    host_information:
      "Mr. William Ship is a visionary entrepreneur with a flair for hospitality. With a diverse portfolio of hotels and resorts under his belt, he has established himself as a leader in the industry. Mr. Ship's innovative approach to hotel management and his focus on guest satisfaction have set a benchmark for excellence in the hospitality sector.",
    host_join_date: "Feb 2024",
    host_response_rate: 100,
    host_fast_response: "within few hours",
    key: true,
    luggage: true,
    shower: true,
    spa: true,
    swimmingPool: true,
    tv: true,
    utensils: true,
    wifi: true,
    bath_a: true,
    bed_a: true,
    parking_a: true,
    kitchen: true,
    hotTube: true,
    jacuzzi: true,
    security: true,
    playArea: true,
    cinemaHall: true,
    frontPorch: true,
    gym: true,
    airConditioning: true,
    balcony: true,
  },
  {
    id: 6,
    username: "user6",
    discount: 10,
    house_image: house_6,
    hall_image: hall_6,
    bed_image: bed_6,
    kitchen_image: kitchen_6,
    swimming_image: swimming_6,
    name: "Unicorn, Gunthorpe By Marston's Inns",
    price: 282000,
    rent: 2820,
    DelarChargeForRent: 2000,
    DelarChargeForBuy: 20000,
    rating: rating,
    review: 5,
    city: "Rajkot, Gujarat",
    beds: 6,
    baths: 3,
    area: 1200,
    parking: false,
    host_img: host_6,
    host_name: "Mrs. Victoria Marston",
    property_information:
      "Unicorn, Gunthorpe By Marston's Inns offers accommodation with amenities such as complimentary WiFi and private bathrooms with bidet, hairdryer, and free toiletries. Unfortunately, outdoor swimming pool, bar, shared lounge, garden, barbecue facilities, terrace, bicycle rental service, car rental service, and cycling nearby are not available.",
    host_information:
      "Mrs. Victoria Marston is a dedicated hotelier with a passion for creating memorable guest experiences. With a background in interior design and hospitality management, she has brought a unique blend of creativity and professionalism to her properties. Mrs. Marston's attention to detail and commitment to quality have earned her accolades from both guests and industry peers.",
    host_join_date: "Dec 2023",
    host_response_rate: 100,
    host_fast_response: "within few hours",
    key: true,
    luggage: true,
    shower: true,
    spa: true,
    swimmingPool: true,
    tv: true,
    utensils: true,
    wifi: true,
    bath_a: true,
    bed_a: true,
    parking_a: true,
    kitchen: true,
    hotTube: true,
    jacuzzi: true,
    security: true,
    playArea: true,
    cinemaHall: true,
    frontPorch: true,
    gym: true,
    airConditioning: true,
    balcony: true,
  },

  {
    id: 7,
    username: "user7",
    discount: 10,
    house_image: house_1,
    hall_image: hall_1,
    bed_image: bed_1,
    kitchen_image: kitchen_1,
    swimming_image: swimming_1,
    name: "Best Western Cedars",
    price: 26000,
    rent: 260,
    DelarChargeForRent: 2000,
    DelarChargeForBuy: 20000,
    rating: 5,
    city: "Rajkot, Gujarat",
    beds: 6,
    baths: 3,
    area: 1200,
    parking: true,
    property_information:
      "The Best Western Cedars Hotel offers accommodation with a range of amenities including an outdoor swimming pool, bar, shared lounge, garden, barbecue facilities, complimentary WiFi, private bathrooms with bidet, hairdryer, and free toiletries. Guests can also enjoy a terrace and avail bicycle and car rental services. Cycling can be enjoyed nearby, although lake views are not provided.",
    host_img: host_1,
    host_name: "Mr. John Smith",
    host_information:
      "Mr. John Smith is a seasoned hotelier with over two decades of experience in the hospitality industry. He is known for his keen eye for detail and commitment to providing exceptional guest experiences. With a background in hotel management, Mr. Smith has successfully overseen the operations of various hotels and resorts, ensuring high standards of service and guest satisfaction.",
    host_join_date: "March 2024",
    host_response_rate: 100,
    host_fast_response: "within few hours",
    key: true,
    luggage: true,
    shower: true,
    spa: true,
    swimmingPool: true,
    tv: true,
    utensils: true,
    wifi: true,
    bath_a: true,
    bed_a: true,
    parking_a: true,
    kitchen: true,
    hotTube: true,
    jacuzzi: true,
    security: true,
    playArea: true,
    cinemaHall: true,
    frontPorch: true,
    gym: true,
    airConditioning: true,
    balcony: true,
  },
  {
    id: 8,
    username: "user8",
    discount: 10,
    house_image: house_2,
    hall_image: hall_2,
    bed_image: bed_2,
    kitchen_image: kitchen_2,
    swimming_image: swimming_2,
    name: "Bell By Greene King Inns",
    price: 250000,
    rent: 2500,
    DelarChargeForRent: 2000,
    DelarChargeForBuy: 20000,
    rating: rating,
    review: 5,
    city: "Rajkot, Gujarat",
    beds: 6,
    baths: 3,
    area: 1100,
    parking: false,
    host_img: host_2,
    host_name: "Ms. Emily Greene",
    property_information:
      "The Bell By Greene King Inns provides accommodation with amenities such as a bar, complimentary WiFi, private bathrooms with bidet, hairdryer, and free toiletries. Unfortunately, outdoor swimming pool, shared lounge, garden, barbecue facilities, terrace, bicycle rental service, car rental service, and cycling nearby are not available.",
    host_information:
      "Ms. Emily Greene is a dynamic entrepreneur who has made significant contributions to the hotel industry. With a passion for hospitality and a knack for innovation, she has played a key role in the development of boutique hotels and upscale accommodations. Ms. Greene's expertise lies in creating unique guest experiences and fostering a culture of excellence within her establishments.",
    host_join_date: "April 2023",
    host_response_rate: 100,
    host_fast_response: "within few hours",
    key: true,
    luggage: true,
    shower: true,
    spa: true,
    swimmingPool: true,
    tv: true,
    utensils: true,
    wifi: true,
    bath_a: true,
    bed_a: true,
    parking_a: true,
    kitchen: true,
    hotTube: true,
    jacuzzi: true,
    security: true,
    playArea: true,
    cinemaHall: true,
    frontPorch: true,
    gym: true,
    airConditioning: true,
    balcony: true,
  },
];

export default Property_Details;
